### ISSUE TITLE
Machine-learning-for-trading to evaluate_trading_signals

### ISSUE THREAD

**Issue by haripaudyal101** [askbuddie/machine-learning#3]
[https://github.com/haripaudyal101/machine-learning-for-trading/blob/a84f5e1856b1fdfee3117d0084d0529270baecb4/12_gradient_boosting_machines/06_evaluate_trading_signals.ipynb](url)

**Comment by ashiishme** [comment]
@haripaudyal101 If you want to contribute, you can create a PR but with the content. Please check other closed PR as an example.
